### ISSUE TITLE
Fork github slow food

### ISSUE THREAD

**Issue by casperjureskog** [CraftAcademy/feb17-slow-food-sinatra#2]
on git hub

**Comment by jocontreras** [comment]
is there a way to edit issues?

**Comment by casperjureskog** [comment]
on git hub

**Comment by jocontreras** [comment]
yes I edited it on github just now...what about deleting a card?

**Comment by casperjureskog** [comment]
hehe dont know :-/

**Comment by Scharrre97** [comment]
Hello! I'm here tooooooo 👍

**Comment by jocontreras** [comment]
Hi Johan...perhaps you can help us find out how to delete a card:)

**Comment by Scharrre97** [comment]
I reading on GH, you cannot delete cards just change them.
